# Parameters of effects

# You can disable each effect by changing enable parameter to false.

# Delay are calculated in seconds.
# If entities-only is disabled, blocks will also be affected by the effect.

EXPLOSIVE:
  enable: true
  power: 2.0
TELEPORTATION:
  enable: true
  entities-only: false
ICE:
  enable: true
  delay: 4
INFLAMED:
  enable: true
  entities-only: false
  delay: 6
HUNGER:
  enable: true
  food: 4
BLOCK_PLACEMENT:
  enable: true
  block: DIAMOND_BLOCK
BUMP:
  enable: true
  vertical-bump: 0.6
PLAYER_INFOS:
  enable: true
REMOVE_EQUIPMENT:
  enable: true
  percent: 50
ROUND_HOLE:
  enable: true
  radius: 2
LIGHTNING:
  enable: true
  entities-only: false
HALLUCINOGENIC:
  enable: true
  delay: 6

# Only lootable arrows from custom bows will be disable if you turn it to false.

lootableArrows: true